#!/bin/bash

set -Eeuo pipefail
set -x

directory=".env"

if [ ! -d "$directory" ]; then
    python3 -m venv $directory
fi

source $directory/bin/activate
pip install -r requirements.txt
pyinstaller --add-data "bdetectionmodel_05_01_23.onnx:." --add-data "ffmpeg:ffmpeg" --collect-data sv_ttk --add-data "img:img" --noconfirm --noconsole --paths ".env" --onedir --contents-directory . --hidden-import=tkinter --hidden-import=PIL._tkinter_finder --name AutoComper autocomper.py
deactivate
read -p "Press enter to continue..."